spring.application.name=api-gateway
spring.cloud.gateway.server.webmvc.routes[0].id=book-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://BOOK-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/books/**
spring.cloud.gateway.server.webmvc.routes[1].id=notification-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/notifications/**
spring.cloud.gateway.server.webmvc.trusted-proxies=127\\.0\\.0\\.1|0:0:0:0:0:0:0:1

server.port=8080

management.endpoints.web.exposure.include=health,info

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}
